import { OnPrintShopDomainConfig } from './OnPrintShopDomainNode';

export const ONPRINTSHOP_PRODUCTS_DOMAIN: OnPrintShopDomainConfig = {
	displayName: 'OnPrintShop Products',
	name: 'onPrintShopProducts',
	description: 'Read OnPrintShop product catalog, category, pricing, FAQ, and SKU matrix data',
	defaultName: 'OnPrintShop Products',
	resources: ['product'],
	defaultResource: 'product',
	operations: {
		product: [
			'getSimple',
			'getManySimple',
			'getDetailed',
			'getManyDetailed',
			'getMasterOptions',
			'getManyMasterOptions',
			'getOptionsRules',
			'getManyOptionsRules',
			'getPrices',
			'getManyPrices',
			'getOptionPrices',
			'getManyOptionPrices',
			'getCategory',
			'getManyCategories',
			'getFAQs',
			'getManyFAQs',
			'getSkuMatrix',
			'getManyOptionGroups',
			'getManyMasterOptionRanges',
			'getManyMasterOptionTags',
		],
	},
};

export const ONPRINTSHOP_PRODUCT_BUILDER_DOMAIN: OnPrintShopDomainConfig = {
	displayName: 'OnPrintShop Product Builder',
	name: 'onPrintShopProductBuilder',
	description: 'Create and maintain OnPrintShop products, categories, prices, sizes, pages, SKUs, and master options',
	defaultName: 'OnPrintShop Product Builder',
	resources: [
		'mutation',
		'product',
		'masterOptionRanges',
		'masterOptionTag',
		'optionFormulas',
		'optionGroup',
		'markupMaster',
	],
	defaultResource: 'mutation',
	operations: {
		mutation: [
			'assignOptions',
			'setAdditionalOption',
			'setAdditionalOptionAttributes',
			'setMasterOption',
			'setMasterOptionAttributePrice',
			'setMasterOptionAttributes',
			'setMasterOptionRules',
			'setMasterOptionTags',
			'setMarkupMaster',
			'setOptionFormulas',
			'setOptionGroup',
			'setProduct',
			'setProductCategory',
			'setProductImage',
			'setProductOptionRules',
			'setProductPages',
			'setProductPrice',
			'setProductSize',
			'setProductSku',
			'setProductsAttributePrice',
			'setQuantityBasedAttributePrice',
		],
		product: [
			'getMasterOptions',
			'getManyMasterOptions',
			'getOptionsRules',
			'getManyOptionsRules',
			'getOptionPrices',
			'getManyOptionPrices',
			'getManyOptionGroups',
			'getManyMasterOptionRanges',
			'getManyMasterOptionTags',
		],
		masterOptionRanges: ['getAll'],
		masterOptionTag: ['getAll'],
		optionFormulas: ['getAll'],
		optionGroup: ['getAll'],
		markupMaster: ['getAll'],
	},
};

export const ONPRINTSHOP_INVENTORY_DOMAIN: OnPrintShopDomainConfig = {
	displayName: 'OnPrintShop Inventory',
	name: 'onPrintShopInventory',
	description: 'Read and update product stock, product stock lists, and master-option stock',
	defaultName: 'OnPrintShop Inventory',
	resources: ['product', 'productStocks', 'masterOptionStock'],
	defaultResource: 'product',
	operations: {
		product: ['getStock', 'updateStock'],
		productStocks: ['getAll'],
		masterOptionStock: [
			'addConfig',
			'deleteConfig',
			'getCombinationMatrix',
			'getConfigs',
			'getHistory',
			'setSettings',
			'updateStock',
		],
	},
};

export const ONPRINTSHOP_ORDERS_DOMAIN: OnPrintShopDomainConfig = {
	displayName: 'OnPrintShop Orders',
	name: 'onPrintShopOrders',
	description: 'Read and update OnPrintShop orders, order products, shipments, batches, quotes, and statuses',
	defaultName: 'OnPrintShop Orders',
	resources: [
		'order',
		'orderDetails',
		'orderShipment',
		'orderProducts',
		'shipToMultipleAddress',
		'batch',
		'quote',
		'quoteProduct',
		'status',
		'mutation',
	],
	defaultResource: 'order',
	operations: {
		order: ['get', 'getAll', 'getShipments', 'createShipment', 'getMany'],
		orderDetails: ['getAll', 'getMany'],
		orderShipment: ['getAll', 'getMany'],
		orderProducts: ['get', 'getMany', 'setDesign', 'updateStatus'],
		shipToMultipleAddress: ['getAll', 'shipToMultipleAddress'],
		batch: ['getAll'],
		quote: ['getAll'],
		quoteProduct: ['getAll'],
		status: ['orderStatus', 'orderProductStatus', 'getStatus', 'getManyStatus'],
		mutation: [
			'addProofVersion',
			'modifyOrderProduct',
			'setBatch',
			'setOrder',
			'setOrderProduct',
			'setProductDesign',
			'setQuote',
			'setShipment',
			'updateOrderProductImages',
			'updateOrderStatus',
			'updateZiflowLinkImages',
		],
	},
};

export const ONPRINTSHOP_CUSTOMERS_DOMAIN: OnPrintShopDomainConfig = {
	displayName: 'OnPrintShop Customers',
	name: 'onPrintShopCustomers',
	description: 'Read, create, and update OnPrintShop customers and customer addresses',
	defaultName: 'OnPrintShop Customers',
	resources: ['customer', 'customerAddress'],
	defaultResource: 'customer',
	operations: {
		customer: ['get', 'getAll', 'create', 'update', 'getMany'],
		customerAddress: ['getAll', 'getMany'],
	},
};

export const ONPRINTSHOP_STORE_ADMIN_DOMAIN: OnPrintShopDomainConfig = {
	displayName: 'OnPrintShop Store Admin',
	name: 'onPrintShopStoreAdmin',
	description: 'Maintain OnPrintShop store, address, department, country, FAQ, markup, and payment-term reference data',
	defaultName: 'OnPrintShop Store Admin',
	resources: [
		'store',
		'storeAddress',
		'department',
		'countries',
		'faq',
		'faqCategory',
		'storeMarkup',
		'paymentTerms',
		'mutation',
	],
	defaultResource: 'store',
	operations: {
		store: ['getAll', 'setStore', 'setStoreAddress', 'storeAddress', 'getCountries'],
		storeAddress: ['getAll'],
		department: ['getAll', 'setDepartment'],
		countries: ['getAll'],
		faq: ['getMany'],
		faqCategory: ['getAll'],
		storeMarkup: ['getAll'],
		paymentTerms: ['getAll'],
		mutation: ['setDepartment', 'setFaqCategory', 'setStore', 'setStoreAddress', 'setStoreMarkup'],
	},
};

export const ONPRINTSHOP_GRAPHQL_DOMAIN: OnPrintShopDomainConfig = {
	displayName: 'OnPrintShop GraphQL',
	name: 'onPrintShopGraphql',
	description: 'Execute raw OnPrintShop GraphQL queries and mutations for API operations not yet modeled as first-class actions',
	defaultName: 'OnPrintShop GraphQL',
	resources: ['graphql'],
	defaultResource: 'graphql',
	operations: {
		graphql: ['execute'],
	},
};
